language: ruby
cache: bundler
env:
  global:
  - CF_API="https://api.cloud.service.gov.uk"
  - CF_ORG="gds-tech-ops"
  - CF_SPACE="docs"
  - CF_USERNAME="philip.potter+tech-docs-deployer@digital.cabinet-office.gov.uk"
  - secure: "l+1jA2zbqjsBXUp19x+4gnbGw4kfvsHYSvzwu3bkO8nRVFaaWm+nd/6be//fiIHnyBydS1/5+dcbO64FQQzjeQczYZlQpCn0uQwfUaYuRBRXPnNSCvxyJXPTm6qRVnDSUxzd8N2rKwi3gVTXJQjC3e0zfDEQM+oEjSzN9QOc5dhm6y+NPlRmKJG9g+iPSOw0DlH+o/X9SxOq2hYlS0XyX/A9WlBWqoylSBZ7NLNYuMzGFipkCUO7YgdV56mPO3FJoxP8PPHI3mfW/CkLXbCggev3WuB6HsJbtRfEThRIyoyFNN04pvfAGdyX037KCBbsm+2ua5f1cjfUI5eVywIiEmawZ88LSOwd6jaWBgT/TtiaNevsxYW/6yOT2NS0Ye87Uz5z0VA2X33sa53t8IbsuA6rAfdTbmpXHj9afk8vYdXWknuJSm1uEWJB6Xdltj1wmpYTKN8lbpS+WNaFKDZo+lQGLcfuiTk67bDk1X//bpEBn+MBIZIqX7ECDOW/oJYtq+aZHbQJmHXQ2oN7BezbEDaAWg4YFGpuLu/yshMwgnSAcP79a3re7RmHvN9NjY9jMVrwwzq0fCtABmUpdKxvIzjs9DoM+HRNnvmhaPD2Evm6sOrWkTQyaY72LCuvkspLSOnRegCAivzpN6YLWD39M5P3+aiN3RvyVWrvBbeQXU0="

branches:
  only:
  - master

before_deploy:
  - export PATH=$HOME:$PATH
  # Install CloudFoundry
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
  - tar xzvf $HOME/cf.tgz -C $HOME
  # Install Autopilot plugin for zero-downtime-push
  - travis_retry cf install-plugin autopilot -f -r CF-Community

script: bundle exec middleman build

deploy:
  - provider: script
    script: ./script/deploy
    skip_cleanup: true
