version: 2
jobs:
  build:
    machine:
      ruby:
        version: 2.4.1
    steps:
      - checkout
      - run:
          name: Check for dead links
          command: |
              gem install awesome_bot
              awesome_bot --allow-dupe --allow-redirect `find . -name '*.md'` --base-url "https://github.com/alphagov/gds-tech-learning-pathway/blob/$CIRCLE_SHA1/"
