version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/ruby:2.5-node
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
              bundle

      - run:
          name: Run danger
          command: bundle exec danger --verbose
